influxdb_development:
  adapter: influxdb
  databasename: k8s
  username: root
  password: root
  server: 23.236.58.68
  port: 8086
influxdb_production:
  adapter: influxdb
  databasename: metrics_db
  username: root
  password: r00tMyPr0ject
  server: 104.154.96.252
  port: 59836
influxdb_staging:
  adapter: influxdb
  databasename: metrics_db
  username: root
  password: r00tMyPr0ject
  server: 104.154.96.252
  port: 59836