influxdb_development:
  adapter: influxdb
  databasename: k8s
  username: root
  password: root
  server: 104.199.152.95
  port: 31876
influxdb_production:
  adapter: influxdb
  databasename: metrics_db
  username: root
  password: r00tMyPr0ject
  server: 104.154.96.252
  port: 59836
influxdb_staging:
  adapter: influxdb
  databasename: metrics_db
  username: root
  password: r00tMyPr0ject
  server: 104.154.96.252
  port: 59836